spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blog_engine}?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Uhbghjcnuhb12
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    username: ${EMAIL_LOGIN:LOGIN}
    password: ${EMAIL_PASSWORD:PASSWORD}
    port: 587
    protocol: smtp
    test-connection: true

blog-engine:
  properties:
    title: Creator
    subtitle: "Art blog"
    phone: "+7 999 999-99-99"
    email: default@email.com
    copyright: "Topchiy Grigoriy"
    copyrightFrom: 2020

server:
  port: ${PORT:8080}